name: Dependabot auto-merge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge patch
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-24.04
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: metadata

      - name: Generate app token
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Approve PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr review "$PR" --approve
        env:
          PR: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Enable auto-merge
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge "$PR" --auto --squash
        env:
          PR: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
